# Generated by Django 2.1.8 on 2019-05-13 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('original_title', models.TextField()),
                ('runtime', models.IntegerField()),
                ('overview', models.TextField()),
                ('poster_url', models.TextField()),
                ('popularity', models.IntegerField()),
                ('actors', models.ManyToManyField(related_name='movies', to='movies.Creator')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Creator')),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.Genre')),
            ],
        ),
    ]
